name = "LARX"
uuid = "633b68c0-f5b4-11eb-9a03-0242ac130003"
authors = ["wmkouw <wmkouw@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.6"
ForneyLab = "0.11.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ForneyLab = "9fc3f58a-c2cc-5bff-9419-6a294fefdca9"
